#+OPTIONS: ^:nil
#+OPTIONS: toc:t H:2
#+AUTHOR: Zhengchao Xu
#+EMAIL: xuzhengchaojob@gmail.com
#+TITLE: 第二次北京马拉松

上午培训，抽空看了下手机，10月30号，突然觉得这个日子有点特别，想了一会，想起是
珊姐的生日，于是登上QQ祝她生日快乐，然后聊了一会。毕业差不多一年半，一直没见，
经常说有空一起吃饭，但是周末经常有事或懒得动。这饭也一直没吃上，照这样，估计要等到明年去
参加她的婚礼的时候才能再见了。^_^

10月就要过去了，细想了一下，这个月发生了两个重要的事：1,国庆长假，回老家把亲订了，也差不多
结束了我妈长达一年的唠叨。2, 10月20号，跑了人生第二个马拉松。

去年跑完人生第一次马拉松之后，我就知道，马拉松这件事，将是我一辈子的事情。只要还能跑得动，
就会一直跑一下去，50岁，60岁，甚至70岁。

这并不是说我去年马拉松跑得很爽，寒冬腊月，糟糕的天气，毫无准备近似“裸跑”的参与。
加上鞋子也不是很好，完全就是自找苦吃。尤其过了24KM之后，有几个朋友在送补给，吃了喝了之后，
发现再也跑不动了，腰/脚都开始疼痛难忍，后十五公里简直是一种“生不如死”的感觉。

但是最终坚持了下来，这就是马拉松的魅力，事实上大部分参赛者在30KM之后都会体力到达极限，
但是“走也要走下来”是大部分人的选择，体力的煎熬和疼痛只有亲身参与过才能体验到。“走也要走下来”
说起来容易，做起来完全是另外一回事。

还好今年的硬件条件要好过去年，没了十八大，比赛恢复到了正常的10月份，天不冷不热，比赛前一天还
刮了一天风，把狗日的雾霾吹得那叫一个干净。国庆回京后，特意去奥特赖斯买了一双NB的跑鞋，本来
想买asics的，但是看上的那款1000,没舍得买，看到NB在打折，就买了一双中档的跑鞋。回来还专门去中央美院
试了一下，感觉还可以。

正所谓“万事具备，只欠東风”，20号不到5点就起了，做早饭，吃完跟女朋友坐公交倒地铁去天安门，
地铁里全是穿比赛衣服的“跑友”，所以我一直称其为“北京城一年一度最大的party”。

在前门跟队伍汇合，五个全马+一个半马，然后出地铁，跨越三个地下通道去比赛出发点。虽然在人数上可以跟世界
顶级马拉松赛事媲美，但北京马拉松的组织一直是被大家骂娘的。从领装备开始就可以看出北马组织的效率之低，
每年领衣服都是几个大妈在发衣服，半天找不到一件，经常要排几个小时的队。比赛当天也一样，从地铁口到出发点
总是得挤个三四十分钟。不过谁让出发点是天安门，安检工作肯定是要做足的，也是没办法。

八点，准时出发，由于与队伍失散，只能自己跑。跑出天安门广场，进入长安街，就看到N多人在起哄，往前一看，
皇城根下站满了一排人，在撒尿。哈哈，顿觉很有趣，后来看到一篇文章，“每年跑一次马拉松，不就为了在皇城根
下撒泡尿吗？”，十分贴切形象。如果历代帝王有知，肯定得气个半死。

没了队伍，一个人不知道怎么跑，就想在路上找个目标跟着，大约跑出两公里，看到一个三人队伍：一个三十多岁的男子
带着两个年轻人，一男一女，也就十五六岁。三人跑得不快，很匀速，看样子应该是比较专业的人。慢慢跟了一会，觉得
他们的速度比较适合我，就决定一直跟着。 就这样，跟在他们后面，跑到了第一个十公里。因为怕掉队，期间一直没有
喝水，直到他们喝了我才喝。前十公里他们一直保持10公里/小时的配速，可能觉得有点慢了，过了十公里后开始加速，
我觉得体力尚可，就跟着一起加速。

到了万泉河，年长的大哥去河边“放水”，我也稍微有点感觉，就跟着一起过去了，不过大哥嘱咐俩年小的还是一直
保持速度。不幸的是，放完水出来就找不到他们了，往前望去全是清一色的马拉松衣服，根本分辨不出来。无奈，只好
又一个人继续跑。

一个人跑，注意力就开始分散了，开始注意身边过去的各种人：一个外国美女，身高得一米八，跑半程，步子迈的超大，
每一步都感觉她用尽了力气，路遇另一个老外，夸她真厉害，她大吼“i am dying”;有个哥们，体重比较胖，竟然
还跑得挺快。还有另一对外国夫妇，得六十开外了，一起跑半程。路上还碰到一个赤脚跑步的队伍，很厉害，赤脚跑
公路还是蛮痛苦的。

我喜欢这样的经历，就跟旅行一样，这种在路上的感觉，我可以遇到各种各样的人，无论年龄，无论肤色，或是喜欢热闹，
或是为了实现目标，或是为了一个承诺，或者，仅仅是对跑步纯粹的热爱。每个人都有自己的故事，然后我们一起构造了
今年的马拉松故事。

有了去年后半段缺水的教训，在半程快结束的时候。我就在供给处拿了一瓶佳得乐，拿在手里跑，后来，就过了半程，好多
人在半程的时候努力冲刺。看他们完成了目标，很替他们高兴。想想我至少还要跑三个小时，腰开始疼起来。


(To be continue)

