#+OPTIONS: ^:nil
#+OPTIONS: toc:t H:2
#+AUTHOR: Zhengchao Xu
#+EMAIL: xuzhengchaojob@gmail.com
#+TITLE: 2013年读过的实体书

毕业之后，开始上班族的生活，公司-家两点一线，下班回去了，
没了寝室集体聊天，也没了跟小刚刚去操场一圈圈跑步，
也没了BRYBT无数的高清电影可以看。读书的时间多了起来。

我一般买技术书比较多一些，尤其是像ULK、CSPP这些经典到爆的”神书“。
而豆花同学会买各种各样的书，漫画、文学等等等等。这个搭配让我很喜欢。

仅以此文，记录我2013年读过的”实体“书籍。

* 1.[《一个人住的每一天》](http://book.douban.com/subject/6387054/)（高木直子）

这是一本漫画书，作者用漫画讲述了自己在东京生活的点点滴滴。包括吃饭、租房、事业等等。

一个人到东京闯荡不容易，尤其是去当漫画家这种成功率很低的职业。
作者在用温馨的基调回忆自己在东京努力奋斗的日子。

以前都是在网上看《火影忍者》、《海贼王》这些风靡全球的漫画，这是第一次看描写真实生活的漫画。
觉得很有趣，日本真是个漫画发展超级成熟的国家。


* 2.[《深夜食堂》](http://book.douban.com/subject/20470917/)（安倍夜郎）

这个系列一共有八本，目前看完了三本。每一本都有十几个小故事组成。

漫画的主人公是一个小饭馆的老板，他的经营时间是晚上10点到早上6点。
店里的菜谱只写了几样菜，但是只要你点，老板基本什么都会做。
会有各种各样的人到这里来吃饭，上班族、相声演员、漫画家、
AV女优...他们有的跟老板很熟，有的则是第一次来。
每个人都有自己喜欢吃的一种食物，每个人都有自己的一个故事。或是爱情、或是亲情、或是事业。

深夜的时候，他们会来到老板的店里，点一个他们喜欢吃的饭，
然后跟老板或其他的客人讲他们的事业或生活，
这些故事都会有一个结尾，可能是好的，也可能是坏的。

老板就这样，每天迎接不同的客人，看生活万态，他很少对别人的事情发表评论，只把他们喜欢吃的东西做好。

在深夜的东京街头，能吃到自己喜欢的食物，就是幸福。

* 3.[《1980年代的爱情》](http://book.douban.com/subject/25696089/)（土家野夫）

故事的大背景是那个荒诞的时代前后，主人公大学毕业，
被分配到偏远宁静的鄂西小镇上，在一次打酒的时候，
遇到了自己喜欢的女同学。

”我知道，当我们谈论爱情时，我们最终是在祭奠那些无邪无辜无欲无悔的青春“。

这本书讲了一个很美很美的爱情故事，和一个再也回不去的时代。

* 4.[《身边的江湖》](http://book.douban.com/subject/25639223/)（土家野夫）

在去杭州的火车上读完了这本书，读完之后想喝酒的冲动特别强烈。

然后那天果真喝了不少酒。在西湖上，月圆风轻，划船的小哥跟我们扯很多杭州的故事，
小船晃来晃去，我一个人自饮晚饭剩下的半瓶“绍兴加饭酒”，
想着许仙和白娘子的故事。

这是本纪实书，野夫写了他很多的朋友，这些朋友和他一样，有着传奇的经历和洒脱的人格。
有时候我会羡慕那些四五十岁的父辈，在他们年轻的时候，正经历着这个国家最好的大学环境，
在没有电脑没有游戏并且不用为毕业发愁的年代，他们有诗、有哲学、有民谣和爱情。

就像高晓松在《[大师照亮八十年代](http://v.youku.com/v_show/id_XNDQwMDU0NDg4.html)》
说的那样:"现在的人可能无法理解当时我们的那种心情——在我们还穿着的确良裤子，穿着棉鞋，
家里只有黑白电视的时候，突然看到了迈克尔·杰克逊，当时我们真的疯掉了！
我们就这样还看到了麦当娜，看到了U2，看到了Guns N' Roses（枪炮与玫瑰）乐队。"。

上半年去电影院看《中国合伙人》，当追求自由浪漫的王阳哭着剪掉一头长发的时候，
心里一阵刺痛。

* 5.[《git 权威指南》](http://book.douban.com/subject/6526452/)（蒋鑫）

一直觉得是linus大神震动世界的第二大“神器”（你知道第一大是什么吗？）

如果有人想深入了解git，我会很推荐这本书。作者是版本控制领域的专家，
他对git的了解和看待git的视角会让你受益匪浅。

* 6.[《Linux内核设计与实现》](http://book.douban.com/subject/6097773/)（Robert Love）

这本书，我每年都会读一遍，每次都有新的收获。

* 7.[《当我谈跑步时我谈什么》](http://book.douban.com/subject/4872222/)（村上春树）

跑步+文艺的书.
