#+OPTIONS: ^:nil
#+OPTIONS: toc:t H:2
#+AUTHOR: Zhengchao Xu
#+EMAIL: xuzhengchaojob@gmail.com
#+TITLE: 五台山

我常想，如果那一天，我有了很多的自由时间，比如两个月以上，我应该会来五台山一趟，
当一个“居士”，五个台的寺庙，都住上一到两天。

早晨，天未亮就起床，到院子里听师傅们做功课，帮忙做早斋。吃完饭后，在寺院附近散步，
跟修行的师傅们聊聊天，感悟一下修行者的思想。或者帮师傅们种种菜，采采花。
中午用过午饭后，就告别这个台，起身前往下一个，慢慢的走，细细的看，感受蓝天、白云、
草地、骏马，以及高山狂野的风。傍晚的时候到达下一个台的寺庙，用过斋饭，天就黑了，
没有阳光的五台山特别冷，只能留在客房里，大通铺，很多旅行者都开始睡觉，
呼噜声此起彼伏，打扫卫生的老师傅最后一个进来，吃一个生萝卜，关灯，上床，
然后不停的念“阿弥陀佛...”。

我不知道自己为什么会有这样的想法，可能在过去某一天的某一时刻，我看到什么东西，
然后这个想法突然就冒了出来，一直存在着。就像我现在每年都会来五台山一样，
不知道为什么要这么做，只是单纯觉得应该这么做。

五台山是我成长的地方，第一次朝台是我体力和意志力的一次飞跃。如果有人问我一些关于旅行、
关于户外的故事。我可能会给他讲讲我第一次朝台的故事，一个挺普通的故事，没有惊险刺激，
但对我却有很大的意义，它是我后来很多事情的精神起点。

出发前一晚，八个人在西站集合完毕，因为没买到卧铺，一上车大家就跑到车厢中部，坐在地上，
聊天，玩杀人游戏。到了半夜1点多，实在撑不住了，就开始坐着睡觉，后来看猿人他们钻到座位底下睡觉，
暗自赞叹这才是户外精神，于是也跟着学了起来，找了个座位钻了下去，穿着新买的、
未穿过的冲锋衣。一进去一股浓浓的脚臭味就扑面而来，强忍着，后来慢慢就睡了一会。不仅心想，
想拜见佛祖果然不是那么容易的。

早晨四点半，火车到站，天未亮，漫天星辰，很冷。出站坐上去鸿门岩的小巴车。第一次踏上山西的土地，
有点好奇，在路上就一直向外看，看山西是否跟传说中的一样到处煤灰。看着看着就睡着了。
晃着晃着就到了朝台的起点：鸿门岩。下车，整理装备，出发去东台。

此时太阳刚从东方升起不久，日光照在东台的山坡上，一片金黄，无比神圣。上山路上，
会看到大大小小 的玛尼堆，我是第一次见这东西，知道它是藏族人民的一种信仰。于是也找了一块石头，
放到了其中的一个玛尼堆上，祈祷这次朝台顺利。

到了东台顶，天已大亮，但阳光还未温暖，寒风凛冽。到台顶的庙里，放下包，去看文殊菩萨的一个佛像，
很多虔诚的妇女在拜。诺大的一片五台山，都是文殊菩萨的道场，每个台都有他的一个分身，
掌管不同的事务。朝台的这两天，无论在哪里，我都觉得会有一股佛的精神力场在包围着这片大地，
在看着你，在感染着你。

东台下来，又回到了下车的鸿门岩，开始走上北台的漫漫长路，这时候太阳已经完全升起，阳光暖暖的，
晒到身上。昨晚睡两个小时觉的副作用立刻被唤醒。在公路上走着走着，竟然开始打盹，做一些断断续续的梦。
走路睡觉，我生平第一次有这种奇妙的经历。后来猿人看大家实在困的不行，就在中间小庙处路边休息，
小灵通在大马路上打起了呼噜。睡了十几分钟，继续赶路，我的脚，就在那时候开始疼了以来。

这次朝台，是我第一次认识鞋子的重要性，对一个行者而言，一双舒服的鞋子就是最好的装备，
这个观念尤其在下午脚疼的没法走路时更为强烈。从小庙开始，路开始上坡，风越来越大，三千米的海拔，
开始有点小高反，头疼。加上以前没走过这种强度的队伍，体力开始跟不上，慢慢拉到了队伍末端。
精神也开始有点涣散。不过还是坚持了下来，并且到了“华北屋脊”。

第一次到“华北屋脊”，很激动，毕竟这是华北最高点，虽然海拔只有三千多一点，但此去向东，直到海边，
已经没有比这还高的地方了。虽然风超大，虽然风很大，大家伙还是果断脱了上衣，
拍一张霸气的肌肉照。

终于，在中午时刻到达了北台顶，我感觉自己已经累得完全没了力气，头痛欲裂，山顶风超大，
也没有什么挡风的地方，所以我们稍微休息了一会，决定继续向前走，找一个离寺庙比较远的地方，
吃有肉的午饭。后来在北台下面的大草甸上，找了两块挡风的大石头，生火做饭，吃完。大家各自找地睡觉一小时，
彻底恢复一下。记得大家当时都在背风坡上睡觉，只有我一个果断走到了向风坡上，因为有阳光。
我已经没了精气神，需要放到阳光下晒晒，补补阳气。

五台山我去了三年，这一次午休，一直是睡得最爽的。我用冲锋衣把头全部捂上，脱掉鞋，风虽然大且冷，
但阳光抵挡了很多的寒气。风声在耳边怒吼，但我很快就在阳光下入睡，并做了一个梦。虽然我忘记了梦的内容，
但可以肯定那是一个正能量的梦，因为醒后我感觉是愉悦的，浑身又充满了力气。

