#+OPTIONS: toc:t H:3
#+AUTHOR: Luis Xu
#+EMAIL: xuzhengchaojob@gmail.com
#+DATE: <2015-12-13 Thu 23:25>

#+TITLE: Orgmode手册5:"捕获"
想象一下到下面的场景: 你在敲着代码,听着歌,突然就来了一灵感, 或者突然QA就
扔给你一个BUG, 你不想打断写代码的思路, 所以只能先把它记下了以后处理. 

"先把它记下来"是个很好的议题, 怎么才能以最快的速度记下来? 
+ 随手记到纸上? 纸张没有提醒功能, 很可能一会就忘记了.
+ 记到提醒软件上. 可能要先离开IDE, 打开提醒软件, 写完再回来.  
  有时候提醒软件的归类功能还不好. 

So, 如果你凑巧用Emacs写代码, Emacs凑巧又装了Org mode, 那恭喜, 
你天然就有了一个"快速且强大"的"捕获"软件: org capture. 
这个功能最大的特性就是在尽量不打搅你现有工作的情况下记录其他的事情.

** 设置capture
在emacs配置文件中加入如下代码, 
#+BEGIN_SRC elisp
     (setq org-default-notes-file (concat org-directory "/notes.org"))
     (define-key global-map "\C-cc" 'org-capture)
#+END_SRC
设置完成后, 你在emacs的任何地方, 按"C-c c"都会打开capture缓冲区, 里面会让你设置任务
设置完成后, 按C-c C-c会自动保存到notes.org文件, 并回到之前的工作窗口.
** 客制化Capture模板
org capture默认会将所有任务都放到notes.org这个文件, 这可能不满足你的
需求, 比如你可能希望将工作和生活的笔记分开, 或者不同的工作笔记放到
同一文件的不同标题下面, 可以通过配置capture模板的方法来完成这个功能.

下面是一个capture模板的例子, 会基于这个例子介绍Capture模板的组成,
在emacs配置中加入下面代码, 这样当使用快捷键(C-c c)进入到capture窗口时, 会显示"t"和"j"两个选项,
+ 按下t会打开buffer让你输入任务, C-c C-c则会将任务分配到gtd.org下的Tasks标题里.
+ 按下j会将任务分配到journal.org文件中.
#+BEGIN_SRC elisp

     (setq org-capture-templates
      '(("t" "Todo" entry (file+headline "~/org/gtd.org" "Tasks")
             "* TODO %?\n  %i\n  %a")
        ("j" "Journal" entry (file+datetree "~/org/journal.org")
             "* %?\nEntered on %U\n  %i\n  %a")))

#+END_SRC

caputre模板主要有下面几部分组成:
1) KEYS. 
   选择模板的快捷键. 如"t"和"j". 只能为字符, 也可以为多个字符.
   实现二级目录.
2) DESCRIPTION. 模板描述.
3) 目录类型. 目前支持的目录类型包括:
   |            | 功能                                                                      |
   |------------+---------------------------------------------------------------------------|
   | entry      | 一个org mode节点, 会被放在指定标题下面(或成为一级标题), 目标文件是org文件 |
   | item       | 同上, 但是为list节点                                                      |
   | checkbox   | checkbox节点                                                              |
   | table-line | 表行                                                                      |
   | plain      | 文本文字                                                                  |
4) 条目格式.
   #+BEGIN_SRC elisp
     %[FILE]     Insert the contents of the file given by FILE.
     %(SEXP)     Evaluate Elisp SEXP and replace with the result.
                       For convenience, %:keyword (see below) placeholders
                       within the expression will be expanded prior to this.
                       The sexp must return a string.
     %<...>      The result of format-time-string on the ... format specification.
     %t          Timestamp, date only. (插入日期)
     %T          Timestamp, with date and time.(插入日期和时间)
     %u, %U      Like the above, but inactive timestamps.
     %i          Initial content, the region when capture is called while the
                 region is active. The entire text will be indented like `%i' itself.
                 (插入调用capture的点, 一般值你当前的工作文件)
     %a          Annotation, normally the link created with `org-store-link'.
     %A          Like `%a', but prompt for the description part.
     %l          Like %a, but only insert the literal link.
     %c          Current kill ring head.
     %x          Content of the X clipboard.
     %k          Title of the currently clocked task.
     %K          Link to the currently clocked task.
     %n          User name (taken from `user-full-name').
     %f          File visited by current buffer when org-capture was called.
     %F          Full path of the file or directory visited by current buffer.
     %:keyword   Specific information for certain link types, see below.
     %^g         Prompt for tags, with completion on tags in target file.
     %^G         Prompt for tags, with completion all tags in all agenda files.
     %^t         Like `%t', but prompt for date.  Similarly `%^T', `%^u', `%^U'.
                 You may define a prompt like `%^{Birthday}t'.
     %^C         Interactive selection of which kill or clip to use.
     %^L         Like `%^C', but insert as link.
     %^{PROP}p   Prompt the user for a value for property PROP.
     %^{PROMPT}  prompt the user for a string and replace this sequence with it.
                 You may specify a default value and a completion table with
                 %^{prompt|default|completion2|completion3...}.
                 The arrow keys access a prompt-specific history.
     %\\n        Insert the text entered at the nth %^{PROMPT}, where `n' is
                 a number, starting from 1.
     %?          After completing the template, position cursor here.(输入完后,光标定位到这里)
   #+END_SRC
5) 属性
