#+OPTIONS: toc:t H:3
#+AUTHOR: Luis Xu
#+EMAIL: xuzhengchaojob@gmail.com
#+DATE: <2015-12-13 Thu 23:25>

#+TITLE: Orgmode手册2:表格
Org mode提供了强大到"令人发指"的表格处理功能, 与excel不同, 
纯文本下编辑表格是另外一种美好的体验.

* 创建表格
在org中任何以"|"字符开头的内容都会认为是
表格的一部分. 在表格当前行按TAB或C-c C-c会格式化表格.
按RET键会自动创建 下一行. 
同时任何以"|-"开头的行都被认为是表格分隔符.

快捷键 *C-c |* 可以创建表格或将选中区域转化为表格, 会询问你创建的表格大小.
如果要转化的区域都含有TAB字符, 会将TAB作为分隔符. 如果为逗号, 会认为是逗号.
否则为空白字符.可以通过前缀强制选择"分隔符":
+ C-u 强制认为是CSV格式(逗号分割), 对于经常处理csv格式的人很有用. 
+ C-u C-u 强制TAB

下表是另外一些操作表格的快捷键. 
| 快捷键               | 功能                   |
|----------------------+------------------------|
| C-c C-c              | 对齐表格               |
| TAB                  | 对齐表格, 移到下一格   |
| S-TAB                | 对齐表格, 移到上一格   |
| RET                  | 对齐表格, 移到下一行   |
| M-a/e                | 移到这一格开始/结尾    |
| M-left/right/up/down | 左/右/上/下移动该行    |
| M-S-left/up/         | 删除当前列/行          |
| M-S-right/down       | 添加新列/行            |
| C-c -/C-c RET        | 添加新分割行           |
| C-c ^                | 排序                   |
| C-c C-x M-w/C-w/C-y  | 粘贴/剪切/复制当前区域 |
| C-c +                | 计算当前列的和         |
| S-RET                | 复制                   |
| C-c `                | 新窗口编辑当前区域.    |
| M-x org-table-import | 导入文件作为表格       |
| C-c                  | 将选中区域表示为表格   |
| M-x org-table-export | 到处表格               |

* 表格宽度和对齐
** 设置列宽度
如果某一列的内容太长, 看上去会比较不美观, 可以通过设置列的宽度来隐藏
一部分内容. 

要设置列宽度, 在这一列的任何的一个空白单元格(没有的话可以创建一个空白行)内
加入 *<N>*, N就是你要设置的宽度.然后按"C-c C-c"即可改变宽度. 
如果该列某一行的宽度大于N, 那么该区域内容会被"压缩", 如果还想查看完整内容, 把
鼠标放到上面即可, 如果要编辑该内容, 在该表格框内按 *C-c `*. 
下图是一个示例:

file:../../../../public/img/org-table2.jpg

当第一次打开文件时, 即使该文件的表格设置了"压缩", 也会看到"压缩"并未发生, 超过宽度的内容
仍然会在表格中显示, 如果想要打开即显示压缩, 可以在文档中加入 *#+STARTUP:align* 来打开这个功能. 
** 设置左右对齐
跟设置宽度一样, 在某一空白区域添加 <r> 或 <l>. 宽度和对齐也可以结合使用:<r10>.
* 引用表中数据
如果要在公式或其他地方使用表格中的数据, 必须要有一种方法可以表示表格中的
一个或一块区域. Org中区域可以通过名称/坐标/相对地址等方式引用. 可以在
单元格上面使用快捷键"C-c ?"来查看该单元格的坐标. 或使用 "C-c }"来显示一块区域.
1. 引用表格的几种方法
 | 格式          | 含义             | 补充                     |
 |---------------+------------------+--------------------------|
 | letter/number | 某一格           | B3表示第三行第二列       |
 | @N            | 某一行           |                          |
 | $N            | 某一列           |                          |
 | @M$N          | 某一格           | @3$2 第三行第二列             |
 | $+/-N         | 当前列的相对列   | 同样适用于行             |
 | $< $>         | 第一列和最后一列 | $<<<倒数第三列, 适用于行 |
 | @I            | high line        | 例如本例第二行           |
 | @0 $0         | 当前行/列        |                          |
2. 使用".."来表示一个区域, 例如 $1..$3表示第一列到第三列
3. 使用 @# $# 来表示当前行/列的值.
4. 命名. org table支持命名方式, 可以通过 "org-table-formula-constants"来设置一个
   全局的名字, 或通过 "#+CONSTANTS"单独为一个文件设置名称变量. 也可以在表格中
   使用emacs的properties功能来使用property变量.
5. 远程引用. 可以通过远程引用的方式引用其他文件或该文件其他表格的内容.
   远程引用的语法为: remote(NAME-OR-ID, REF). 第一个参数可以是本文件中
   用 #+NAME 来命名的表格, 或其他文件中的一个entry ID. REF是当前表格的一个区域.
* 表格处理计算
文章开始说过, org mode提供了各种表格计算功能, 下面就看一下具体的操作,

表格计算可以在表格底部用"#+TBLFM:"关键字, 后面接计算公式, 目前
表格支持 "Calc" 和 lisp计算公式. 如下图表格, 公式
"#+TBLFM: $5=$1+$2+$3+$4" 用于计算前四列的和, 并将结果写入第五列.

file:../../../../public/img/org-table.png

注: Calc中"/"的优先级低于"*". 所以公式 *$4=$1/$2*$3* 实际为 
*$4=$1/($2*$3)*.
** 附加模式. 
附件模式可以用于计算特定格式的内容, 或者格式化数据.
org支持公式后面添加任意数量的附加模式, 公式和
附加模式之间用";"隔开. 目前支持的附加模式包括:
   | 表示        | 意义                              |   |
   |-------------+-----------------------------------+---|
   | pN          | 计算精度                          |   |
   | nN,sN,eN,fN | 普通/科学/工程/固定表示           |   |
   | D/R         | 度/弧度模式                       |   |
   | F/S         | 小数模式                          |   |
   | T/t         | 时间计算模式                      |   |
   | E           | 控制怎样表示空白格                |   |
   | N           | 把所有表格表示为数字, 非数字0代替 |   |
   | L           |                                   |   |

   下面是一些实例程序
    #+BEGIN_SRC elisp
     $1+$2                Sum of first and second field
     $1+$2;%.2f           保留小数点两位
     exp($2)+exp($1)      数学公式
     tan($1);Dp3s1        计算度数, 精度为3, 展示为科学计数
#+END_SRC
** lisp代码处理表格.
   org支持用lisp代码处理表格. 以 '( 开头的表达式会被解析为lisp代码,
   默认情况下, 表格的内容会被引用为字符串, 如果需要将其处理为数字,
   需要将其转化为N模式(后面加";N"). 也可以用使用双引号将其表示为字符串.
   "范围(..)"会被解析为空格分开的域. 例如前面表格相加的公司用lisp表示为
   *$5='(+ $1 $2 $3 $4)*. 下面是一些例子:
   #+BEGIN_SRC elisp
'(concat (substring $1 1 2) (substring $1 0 1) (substring $1 2))
   交互第一列表格内容的前两个字符
'(+ $1 $2);N   Add columns 1 and 2, equivalent to Calc's `$1+$2'.
'(apply '+ '($1..$4));N   另外一种表格相加方法
   #+END_SRC
** 时间计算.
 前面讲过表格支持时间计算.表格支持的时间格式为 HH:MM[:SS], 
 其中SS是可选, 如果公式后面接";T", 计算结果会展示为 HH:MM:SS.
 如果为";t", 计算结果为小时的小数表示. 下面的例子展示了这一点:
 #+BEGIN_SRC elisp
     |  Task 1 |   Task 2 |    Total |
     |---------+----------+----------|
     |    2:12 |     1:47 | 03:59:00 |
     | 3:02:20 | -2:07:00 |     0.92 |
     #+TBLFM: @2$3=$1+$2;T::@3$3=$1+$2;t
 #+END_SRC
** 直接在某一格中输入公式. 
 可以直接在域中输入公式. 在域中输入":="并后面接公式. 也可以
 在当前域中输入 "C-u C-c ="命令在提示框中输入公式.
** 查找功能
orgmode提供了三个查找函数用于在表中进行查找:
+ (org-lookup-first VAL S-LIST R-LIST &optional PREDICATE)
  在S-LIST中查找第一个 (PREDICATE VAL S)值为t的S. 并返回R-LIST与S位置相同的
  值. PREDICATE的默认值为 equal, 如果R-LIST为nil, 则返回S.
+ (org-lookup-first VAL S-LIST R-LIST &optional PREDICATE)
  与上一个函数意义相同, 不过是先查找最后一个.
+ (org-lookup-first VAL S-LIST R-LIST &optional PREDICATE)
  相似函数. 不过返回的是一个列表.

下面是一个示例, 更多示例看这篇文章: http://orgmode.org/worg/org-tutorials/org-lookups.html
#+BEGIN_SRC elisp
 #+TBLNAME: rates
| currency        | abbreviation | euros |
|-----------------+--------------+-------|
| euro            | eur          |     1 |
| Norwegian krone | nok          |  0.14 |
| Swedish krona   | sek          |  0.12 |
| US dollar       | usd          |  0.77 |

#+TBLNAME: cost
|  date | expense          |  sum | currency |   rate |  euros |   |
|-------+------------------+------+----------+--------+--------+---|
|  1.3. | flights          |  324 | eur      |      1 |    324 |   |
|  4.6. | books and maps   |  243 | usd      |   0.77 | 187.11 |   |
| 30.7. | rental car       | 8300 | sek      |   0.12 |   996. |   |
|  2.7. | hotel            | 1150 | sek      |   0.12 |   138. |   |
|  2.7. | lunch            |  190 | sek      |   0.12 |   22.8 |   |
|  3.7. | fishing licenses | 1400 | nok      |   0.14 |   196. |   |
|  3.7. | gasoline         |  340 |          | #ERROR | #ERROR |   |
 #+TBLFM: $5='(org-lookup-first $4 '(remote(rates,@2$2..@>$2)) '(remote(rates,@2$3..@>$3)))::$6=$5*$3
函数解释第一个函数查找cost表的第四列和rates表的第二列相同的值, 并将查找结果对应的
rates表的第三列填充到cost表的第五列, 然后计算第六列的值.
#+END_SRC
** 调试公式
org mode提供了下列用于调试公式的快捷键:
| 快捷键            | 功能                   |
|-------------------+------------------------|
| C-c = / C-u C-c = | 在当前格写入公式       |
| C-u C-u C-c =     | 重新插入公式           |
| C-c ?             | 当前格信息             |
| C-c }             | 表信息                 |
| C-c {             | 打开/关闭调试          |
| C-c '             | 在buffer中编辑所有公式 |
|                   |                        |
* 其他特性
** 列组
Org导出表格时, 默认是以行为单位, 也可以按列为单位来处理数据.
这需要添加一个特殊行: 该行的第一个区域只包含"/", 其他以"<"表示的区域
表示是一个组的开始, 以">"结束表示组的结束.
** Orgtbl 模式
如果想在其他的mode下使用org mode的table功能, 可以输入命令 "orgtbl-mode".
