#+OPTIONS: toc:t H:3
#+AUTHOR: Luis Xu
#+EMAIL: xuzhengchaojob@gmail.com
#+DATE: <2015-12-13 Thu 23:25>

#+TITLE: Orgmode手册3:链接
在Org mode里可以创建通过创建链接的方式引用其他的内容,
目前Org 支持如下链接方式: 文件内部, 外部文件, Usenet文章, 邮件及其他.

** 链接格式
   Org的链接格式为:
#+BEGIN_EXAMPLE
[[链接地址][描述]] 或 [[链接地址]]
#+END_EXAMPLE
当最后一个"]"写完时, org会将该链接显示为(带下划线的"描述", 该显示格式对应face "org-link"),
如果想要编辑链接, 可以在链接上使用快捷键 "C-c C-l", 在显示内容前后使用"delete"键
会破坏链接的语法(也可以这样编辑链接). 

下面是一些链接的快捷键
|             | 功能                    |
|-------------+-------------------------|
| C-c l       | 将当前位置存为一个link  |
| C-c C-l     | 编辑/插入链接           |
| C-c C-o     | 打开(跳转)              |
| C-u C-c C-l | 插入文件                |
| C-c C-x C-v | 开关图片显示            |
| C-c %       | 将当前位置放入mark ring |
| C-c &       | 返回mark ring           |
| C-c C-x C-n | next link               |
| C-c C-x C-p | 上一个link              |
** 内部链接
如果一个链接不是一该URL, org会将其看做内部链接, org寻找内部链接的方式为:
1) 跳转到被 "<<>>"定义的地方. 如下面的例子,在第一个链接上用C-c C-o 会
  跳转到test出现的地方. 
  #+BEGIN_EXAMPLE
  loc1: [[test]] 
  loc2  this is a <<test>>
  #+END_EXAMPLE
2) 如果1)不存在, 会跳转到 "#+NAME" 命名和链接相同的地方.
3) 前两步都失败, 会尝试寻找精确匹配的 *标题*.
** 外表链接
org mode支持的外部链接包括:
#+BEGIN_EXAMPLE
|                             | 描述                  |
|-----------------------------+-----------------------|
| http://web                  | 网站                  |
| doi:10.1000/182             | doi链接               |
| file://path                 | 文件相对/绝对地址     |
| file:/a@b:x/y.pdf           | 远程文件地址          |
| file:orgmode-learn.org::111 | 跳转到文件NNN行       |
| file:org-file::key/*title   | 支持org文件的标题搜索 |
| file+sys:/path              | 使用系统打开          |
| docview:path::NNN           | 使用docview模式打开   |
| news:comp.emacs             | Usenet 链接           |
| mailto:a@b                  | mail                  |
| gnus:group                  | gnus链接              |
| irc:/irc.com/#emacs         | irc链接               |
| shell:cmd                   | shell 命令            |
| elisp:cmd                   | elisp cmd             |
#+END_EXAMPLE

** 短链接
如果链接太长且在文件中经常使用, 可以将其设置为"链接关键字",
可以用 "#+LINK"关键字来实现这个功能, 或者设置"org-link-abbrev-alist"变量:
#+BEGIN_EXAMPLE
     #+LINK: bugzilla  http://10.1.2.9/bugzilla/show_bug.cgi?id=
     #+LINK: google    http://www.google.com/search?q=%s
     或者
     (setq org-link-abbrev-alist
       '(("bugzilla"  . "http://10.1.2.9/bugzilla/show_bug.cgi?id=")
         ("url-to-ja" . "http://translate.google.fr/translate?sl=en&tl=ja&u=%h")
         ("google"    . "http://www.google.com/search?q=")
         ("gmap"      . "http://maps.google.com/maps?q=%s")
         ("omap"      . "http://nominatim.openstreetmap.org/search?q=%s&polygon=1")
         ("ads"       . "http://adsabs.harvard.edu/cgi-bin/nph-abs_connect?author=%s&db_key=AST")))
#+END_EXAMPLE

短链接的格式为, 如果链接中有"%s", 会被tag替代, "%h"则会将tag进行url编码.
%(function)会调用函数并将结果添加. 什么都没有的话直接在尾部添加. 例如
#+BEGIN_EXAMPLE
[[bugzilla:129][description]] ;;  http://10.1.2.9/bugzilla/show_bug.cgi?id=129
#+END_EXAMPLE
